### PR TITLE
Return more complete error messages in verify_init_function and verify_entry_function.

### PR DESCRIPTION
**Pull request by steelgeek091**
Return more complete error messages when executing `verify_entry_function` and `verify_init_function`.
`verify_entry_function` returns the `PartialVMError` error type, and `verify_init_function` returns the `VMError` error type.

resolve https://github.com/rooch-network/rooch/issues/243.

### CODE REVIEW

**Review by jolestar — COMMENTED** [review]
Change the `Result<bool>` to `VMResult<bool>` ?

**Comment by steelgeek091** [comment]
> Change the `Result<bool>` to `VMResult<bool>` ?

I think this is possible, as the verifier is actually part of MoveVM. 

Therefore, it would be appropriate to add `PartialVMResult`:

```rust
pub type VMResult<T> = ::std::result::Result<T, VMError>;
pub type PartialVMResult<T> = ::std::result::Result<T, PartialVMError>;
```

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
@steelgeek091 you can change it in this PR or next PR.

**Comment by steelgeek091** [comment]
> @steelgeek091 you can change it in this PR or next PR.

I will make the changes in this PR immediately.

**Pull request merged**
