### PR TITLE
[gh-1644] add groth16 verification support.

### LINKED ISSUE #1644: [moveos_std] Support Groth16 proof verifier
Ref: https://github.com/MystenLabs/sui/blob/7c5cc3f52518d811be787b5395494a6f88a51ee9/docs/content/guides/developer/cryptography/groth16.mdx#verification-in-sui

### PR DESCRIPTION
**Pull request by feliciss**
## Summary

Add preparation of verifying key and verification of Groth16 proof based on Sui implementation.

- Closes #1644

### CODE REVIEW

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
Merge to #2167

**Comment by feliciss** [comment]
> Merge to #2167

There's still an issue with CI not resolved this time:

```zsh
FAIL [  23.946s] rooch-genesis tests::test_builtin_genesis_init

--- STDOUT:              rooch-genesis tests::test_builtin_genesis_init ---

running 1 test
2024-07-13T13:48:41.456926Z  INFO moveos::moveos: execute genesis tx state_root:0xf45479fee655cd3c69b1b5dc420eee95c7f127d78cc725eae51858ccee926100, state_size:31    
2024-07-13T13:48:41.495790Z  INFO rooch_genesis::tests: genesis init test case for network: 4
2024-07-13T13:48:48.277813Z  INFO moveos::moveos: execute genesis tx state_root:0xf45479fee655cd3c69b1b5dc420eee95c7f127d78cc725eae51858ccee926100, state_size:31    
2024-07-13T13:48:55.094905Z  INFO moveos::moveos: execute genesis tx state_root:0x5ea3daa455da2ca26499ddb309511089c6b4b17028f9acb3170cccb5a4b5acb1, state_size:31    
2024-07-13T13:48:55.129989Z  INFO rooch_genesis::tests: genesis init test case for network: 3
2024-07-13T13:49:00.558654Z  INFO moveos::moveos: execute genesis tx state_root:0x5ea3daa455da2ca26499ddb309511089c6b4b17028f9acb3170cccb5a4b5acb1, state_size:31    
2024-07-13T13:49:01.123216Z  INFO rooch_genesis::tests: genesis init test case for network: 2
test tests::test_builtin_genesis_init ... FAILED

failures:

failures:
    tests::test_builtin_genesis_init

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 23.93s


--- STDERR:              rooch-genesis tests::test_builtin_genesis_init ---
thread 'tests::test_builtin_genesis_init' panicked at frameworks/rooch-framework/src/natives/mod.rs:91:87:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
------------
     Summary [  24.229s] 266 tests run: 265 passed, 1 failed, 0 skipped
        FAIL [  23.946s] rooch-genesis tests::test_builtin_genesis_init
error: test run failed
Error: Process completed with exit code 100.
```

Which is:

```zsh
called `Option::unwrap()` on a `None` value
```

**Comment by jolestar** [comment]
New native function need to reset the testnet genesis, or make the gas parameter to optional.

**Comment by feliciss** [comment]
> New native function need to reset the testnet genesis, or make the gas parameter to optional.

Okay.

**Comment by feliciss** [comment]
> New native function need to reset the testnet genesis, or make the gas parameter to optional.

Is there a command to reset that or it will be automatically reset?

**Pull request merged**
