### PR TITLE
Add the data_struct attribute to ObjectID

### PR DESCRIPTION
**Pull request by steelgeek091**
resolve https://github.com/rooch-network/rooch/issues/2086
resolve https://github.com/rooch-network/rooch/issues/2085

### CODE REVIEW

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
Also add #[data_struct] to string::String and ascii::String?

**Comment by steelgeek091** [comment]
> Also add #[data_struct] to string::String and ascii::String?

Added #[data_struct] to string::String and ascii::String, but need to update the test net's genesis file.

**Comment by jolestar** [comment]
@steelgeek091 

cargo run --package framework-release --bin framework-release -- -v 1
cargo run -p rooch-genesis -- -n test

**Comment by steelgeek091** [comment]
> @steelgeek091
> 
> cargo run --package framework-release --bin framework-release -- -v 1 cargo run -p rooch-genesis -- -n test

Got it, the genesis file has been updated.

**Review by baichuan3 — APPROVED** [review]

**Pull request merged**
