### PR TITLE
[naming] unify this in function parameters to self, fix and add docs.

### LINKED ISSUE #324: [Framework & Stdlib] Unify self and this in Move module
Some modules we use `this` and some modules we use `self`, need to be unified.

https://github.com/rooch-network/rooch/blob/ca178fe2e0a96a41167fda24b405b391ff56637d/crates/rooch-framework/sources/authenticator.move#L63-L87

https://github.com/rooch-network/rooch/blob/ca178fe2e0a96a41167fda24b405b391ff56637d/moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move#L46-L71

### PR DESCRIPTION
**Pull request by feliciss**
resolves #324

### CODE REVIEW

**Review by wow-sven — APPROVED** [review]

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
@feliciss help to rebase and resolve conflicts.

**Comment by feliciss** [comment]
> @feliciss help to rebase and resolve conflicts.

Done.

**Comment by feliciss** [comment]
New file is added a whitespace so it's easy to find it:

```rust
fun remove_resource_from_account_storage<T: key>(self: &mut AccountStorage): T {
      assert!(type_table::contains_internal<T>(&self.resources), EResourceNotExists);
      type_table::remove<T>(&mut self.resources)
  }
```

**Comment by feliciss** [comment]
Need to rerun the CI test or force merge the PR.

**Pull request merged**
