### PR TITLE
[Bitcoin] Handle coinbase transaction for Ord

### LINKED ISSUE #1505: [Bitcoin] Handle coinbase Tx by SealPoint
### Problem
There is a problem with the current SealPoint implementation. Since there is a Gas fee for BTC transactions, when a part of the sat in the UTXO is spent as Gas when transferring, if this part of the Gas contains any Inscription, it means that these Inscriptions are burned (given miner).
Every time a transfer occurs, the offset of the Inscription in the new UTXO will be recalculated.

How to calculate the offset in the above scenario and solve the problem of Inscription being burned.

### Relative txs:
Inscribe Inscriptions:
https://mempool.space/tx/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc

Transafer Inscriptions once:
https://mempool.space/tx/53c2ddacc7548b7350bea571567b26e1dc08fd49b3b658819a045a7bf5faa466

Transafer Inscriptions twice:
https://mempool.space/tx/b3d9c7a005e6dcaef0734eeccfa2f59bc42004ca210679bf665267d95b997574

Transafer Inscriptions three times:
https://mempool.space/tx/e6b157e55c9968e4fe43f36d8251a89909793aabe930bff36248c5cb28838087

Coinbase tx:
https://mempool.space/tx/32d21f0a4835fa55c889ea1e1a8dc4381917149ec2a54682959baf280bd52fe2

### Case 1

inscription id = 092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci7

owner match successfully.

offset in Rooch: 61672
offset in Ord: 62052

Rooch
```
curl --location 'http://localhost:10051' \
--header 'Content-Type: application/json' \
--data '{
    "id": 101,
    "jsonrpc": "2.0",
    "method": "btc_queryInscriptions",
    "params": [
        {"inscription_id":{"txid":"092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc", "index":7}}, null, "1", true
    ]
}'
```

```
{
    "jsonrpc": "2.0",
    "result": {
        "data": [
            {
                "object_id": "0x03148f347c11a581f78984d516b05d8bc6ef4f7c51a15137e5d183772e44323a",
                "owner": "0x3de7da76f19b80a4b76ebffd169c49d29c2204028b3b5f6b5d4b3b097bf198c7",
                "owner_bitcoin_address": "3MSqmLCmL5XW1PbUnabyLtkYdLXePGokCu",
                "flag": 0,
                "value": {
                    "txid": "0xcc415c5b2556fd49599a84fe5a39d77fcce8821979ab053f5f02a882e8112109",
                    "bitcoin_txid": "092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc",
                    "index": 7,
                    "offset": 61672,
                    "body": "0x89504e470d0a1a0a0000000d49484452000003e8000003e80403000000bf8dc9d70000002a504c5445648596020202ffdeb0f8faf9faa632c562908687880000005c390fc77514878788090909d7d1d1dd5d2e33b02b08000006fd494441547801eddc216833671cc7f1df25d9fb8ea9f79887725e14e2bd179bae9a9e5be56c5d75d5f4bc8c988740bd08f5e6a2060d4d3233261ef384ec925c93cf4797a7812fff93bf5c0b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a009ff6953d7e7f39b845b21bae8888ee8888ee8888ee8888ee8888ee8888ee8888ee81444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1119d998519978ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8d89cb130e3d2111dd1111dd1111dd1111dd1111dd1111dd1111dd145477444477444477444477444477444477444477444477444171dd1313f32ba9590fd3a55cdb730f64b477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d744447744447744447744447746cce1cb01eb36fc6f7032b7a978ee8888ee8888ee8a3203aa2233aa2233aa2233aa2233aa2233aa28b8ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8884e934b6a53ea52d8af5398dca5b01cd928cedae64c01d1c74974444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd19965e4a6f314b6af29fc7857f99b01cdeb6323bbb54b477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d744447744447744447746cce0c64dfa7303d60a96699234cef53d5b4296c73365f1e52d8fce1d211fdf3121dd1111dd1111dd145477444477444477444477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1b139f3b1a8efc91c629eba650671c8e04defd24b888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8981f59a56abbcca0cef0af7e49e9292e1dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd1b13933cf20b6af29fc96baa714a6f7f587bffe9aaadea523fa35f279e7c5a523fa68898ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233a4609da9c48d3baf48b4274444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd14547744447744447744447744447744447744447746cce4ce7293ca66e7eccc3dbc7631e5ea6d4bbf441203aa28b8ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2637e64bf3edbc3bbd4f53991cd4b0a3ffc99c2df0f95e8d7abcb894c3a9f7744ffa444477444477444477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1119d998599ff390db37b1b660d659552efd2111dd1111dd1115d7444477444477444477444477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111d9b33fbf5b8cea6abafd0b87444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d7444477444477444477444e75a376798742e9d1b8d8ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8981fe1fbdf5358e46cde7f76e9dc5a74444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd14547744447744447744447744447744447744447746cceecde52e84eb527f3f1570adfb529fc941369bea5b0f99ac2fbb34be7dfe8888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8a2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa2d3e492da94e639c27e9daa55ea4eb64bb3c8d9bc3fbb74444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd14547744447744447744447744447744447744447740e35cb1568dafa204997ba5506f1657173d1d9bca4d0fbbc233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8a2233aa2233aa2233aa2637ee4822b347deaba14766fd5311b978ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8a2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa28b8ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa28b8ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee89cdf3f6b886612d648c2750000000049454e44ae426082",
                    "content_encoding": null,
                    "content_type": "image/png",
                    "metadata": "0x",
                    "metaprotocol": null,
                    "parent": null,
                    "pointer": null
                },
                "object_type": "0x4::ord::Inscription",
                "tx_order": 1520,
                "state_index": 0,
                "created_at": 0,
                "updated_at": 0
            }
        ],
        "next_cursor": {
            "tx_order": 1520,
            "state_index": 0
        },
        "has_next_page": false
    },
    "id": 101
}
```

Ord
```
https://ordinals.com/inscription/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci7
```

```
id
092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci7
charms
👹
address
3MSqmLCmL5XW1PbUnabyLtkYdLXePGokCu
value
65980
sat
[1892382503042808](https://ordinals.com/sat/1892382503042808)
preview
[link](https://ordinals.com/preview/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci7)
content
[link](https://ordinals.com/content/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci7)
content length
1900 bytes
content type
image/png
timestamp
2023-03-21 00:10:03 UTC
height
[781735](https://ordinals.com/block/781735)
fee
1000
reveal transaction
[092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc](https://ordinals.com/tx/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc)
location
e6b157e55c9968e4fe43f36d8251a89909793aabe930bff36248c5cb28838087:34:62052
output
[e6b157e55c9968e4fe43f36d8251a89909793aabe930bff36248c5cb28838087:34](https://ordinals.com/output/e6b157e55c9968e4fe43f36d8251a89909793aabe930bff36248c5cb28838087:34)
offset
62052
ethereum teleburn address
0x7EC6B5196fD0889afa4Ec2b5D5Bbb4B0455b9F06
```

### Case 2

inscription id = 092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci93

owner match failure.

offset in Rooch: 6666
offset in Ord: 15485345 (Another transfers occurred after xxxe6b157e55c9968e4fe43f36d8251a89909793aabe930bff36248c5cb28838087 )

Rooch
```
curl --location 'http://localhost:10051' \
--header 'Content-Type: application/json' \
--data '{
    "id": 101,
    "jsonrpc": "2.0",
    "method": "btc_queryInscriptions",
    "params": [
        {"inscription_id":{"txid":"092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc", "index":93}}, null, "1", true
    ]
}'
```

```
{
    "jsonrpc": "2.0",
    "result": {
        "data": [
            {
                "object_id": "0x3419b5cd307993c8ea143f79820b0bee6bfbb74e4d29310abb5ca4d973a7e3d8",
                "owner": "0x816985f121a97cfc1ba2fe04d2aa5a0510ffda062bec3868ca76607ab44e4926",
                "owner_bitcoin_address": "bc1pwr2xlylgsxr0dgnhh5mvr6vwv6zdn60jgn05xl46udlzqyecc2nq7zva0x",
                "flag": 0,
                "value": {
                    "txid": "0xcc415c5b2556fd49599a84fe5a39d77fcce8821979ab053f5f02a882e8112109",
                    "bitcoin_txid": "092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc",
                    "index": 93,
                    "offset": 6666,
                    "body": "0x89504e470d0a1a0a0000000d49484452000003e8000003e80403000000bf8dc9d70000001e504c5445648596020202ffdeb0f8faf9faa632c56290000000ffe400988880596570897cf18000000638494441547801eddc318eda501885d16b404a8b950d445e4124ef2975b6912e75b690b58c342b40ecc06e5380d3bf295ef40263189f532264019f7eca1b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000783074792c7daa9639ff855d101dd1d96874444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd139e4c175c714966ef5159ae203564d71e9888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ecd993ea5a1be27b31f53b8bcbedb0a4d77acbfb2cc2e1dd1111dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774d1111dd1111dd1111df3232d5ac64676f5f7dccafe6b7d6ce46a7e04d1111dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774d1111dd1111dd1111dd1b139732bcb94c2bebe54733f5d9fc2c5a5f31cd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774baace95b4a2f295ccf797ecb6c73660b2abb3493bf7756888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233a87556785fa94c6943ea7eaf29ac2a7ef69f02315ad0ffef373e3978ee8888ee8888ee8888ee8888ee8a2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa28b8ee8888ee8888ee8888ef9915fff3048724a83fd58ff5a7d4a534a63cbefd51d535866978ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8d89c79eb77cbec4b9b2977b24c2e1dd19f85e8888ee8888ee8888ee8888ee8888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa2233a5dd6d4a734661b5e529a5c3aa2bf37d1111dd1111dd1111dd1111dd1111dd1111dd1111dd145477444477444477444477444477444477444477444477444e7900f6999d3a06f7fb04b4774444774444774444774444774444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd14547744447744447746cceacb930d3604a83eb390d86944e294d2e1dd1111dd1111dd1454774444774444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd1111dd1b139b3cc8f7536c3db151a978ee85b213aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8a2233aa2233aa2637386dde0d2117d1344477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d7444477444c7fc08a7d4edbeb87444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d7444477444477444477444c7e6ccdd5ccf290cb993c1a523fad3101dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd145477444477444477444477444477444477444477444477444a7cb9afa94c63458e6549dd69c8f39a56e72e9888ee8888ee8888ee8882e3aa2233aa2233aa2233aa2233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8981fb98965bed74a4893c9a5233aa2233aa2233aa2233aa223bae8888ee8888ee8888ee8888ee8888ee8888ee8888ee8888ee8a2233aa2233aa2233aa2233a753667569e7db99e6b63362e1dd1111dd1111dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd145477444477444477444477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d7444477444477444477444477444477444477444477444477444171dd1111dd1111dd1111dd1111dd1111dd1111dd1111dd1115d74444774444774444774444774444774444774444774444774d1111dd1111dd1111dd1111dd159c15ff965561129c9a5bf0000000049454e44ae426082",
                    "content_encoding": null,
                    "content_type": "image/png",
                    "metadata": "0x",
                    "metaprotocol": null,
                    "parent": null,
                    "pointer": null
                },
                "object_type": "0x4::ord::Inscription",
                "tx_order": 1464,
                "state_index": 970,
                "created_at": 0,
                "updated_at": 0
            }
        ],
        "next_cursor": {
            "tx_order": 1464,
            "state_index": 970
        },
        "has_next_page": false
    },
    "id": 101
}
```

Ord
```
https://ordinals.com/inscription/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci93
```

```
id
092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci93
charms
👹
address
12VBZiPhgwu36ZbGYZf3BzVT1EE5yBmLa2
value
403319640
sat
[1924487984396002](https://ordinals.com/sat/1924487984396002)
preview
[link](https://ordinals.com/preview/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci93)
content
[link](https://ordinals.com/content/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cci93)
content length
1691 bytes
content type
image/png
timestamp
2023-03-21 00:10:03 UTC
height
[781735](https://ordinals.com/block/781735)
fee
1000
reveal transaction
[092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc](https://ordinals.com/tx/092111e882a8025f3f05ab791982e8cc7fd7395afe849a5949fd56255b5c41cc)
location
f215a314018d89e064009c1256a0d8fcdbc4d3576d746caadbd0d514bb55936b:0:15485345
output
[f215a314018d89e064009c1256a0d8fcdbc4d3576d746caadbd0d514bb55936b:0](https://ordinals.com/output/f215a314018d89e064009c1256a0d8fcdbc4d3576d746caadbd0d514bb55936b:0)
offset
15485345
ethereum teleburn address
0x9EB6458B5445C72492892d20519A033A44FdaFbd
```

### PR DESCRIPTION
**Pull request by baichuan3**
## Summary

Process the coinbase transactions in the block, pay the block reward + all transaction fees to the miners, and process the Ord Satpoint transfer.

- Closes #1505

### CODE REVIEW

**Comment by adshao** [comment]
This pr looks good to me.

However, in my opinion, there are still some issues about the inscription code:
* Transfer and inscribe may happen at the same transaction, but we assume a transaction is either transfer or inscribe [here](https://github.com/rooch-network/rooch/blob/b49d0697d617ff71b6b0b79fe9752d5aefaf6a46/frameworks/bitcoin-move/sources/light_client.move#L163)
* The logic of [process_transaction](https://github.com/rooch-network/rooch/blob/b49d0697d617ff71b6b0b79fe9752d5aefaf6a46/frameworks/bitcoin-move/sources/ord.move#L260) to inscribe new inscriptions is not equal to the original implementation of ord, which may cause inconsistent inscriptions
* We need an unit test framework to make sure all the test cases of inscription in [ord](https://github.com/ordinals/ord/blob/c749c47325c4d86f4351d523b40791aa05e0fb24/src/index.rs#L2528) are also passed in rooch

**Comment by baichuan3** [comment]
> * inscriptions
Can you describe the specific differences in inscribing new inscriptions?

**Comment by adshao** [comment]
> > * inscriptions
> >   Can you describe the specific differences in inscribing new inscriptions?

For example, 
`is_seperate_outputs` is unnecessary [here](https://github.com/rooch-network/rooch/blob/b49d0697d617ff71b6b0b79fe9752d5aefaf6a46/frameworks/bitcoin-move/sources/ord.move#L276), `offset` should be determined by [pointer](https://github.com/ordinals/ord/blob/c749c47325c4d86f4351d523b40791aa05e0fb24/src/index/updater/inscription_updater.rs#L191)

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
> > > * inscriptions
> > >   Can you describe the specific differences in inscribing new inscriptions?
> 
> For example, `is_seperate_outputs` is unnecessary [here](https://github.com/rooch-network/rooch/blob/b49d0697d617ff71b6b0b79fe9752d5aefaf6a46/frameworks/bitcoin-move/sources/ord.move#L276), `offset` should be determined by [pointer](https://github.com/ordinals/ord/blob/c749c47325c4d86f4351d523b40791aa05e0fb24/src/index/updater/inscription_updater.rs#L191)

`is_separate_outputs` need to be removed after SatPoint implemention.

**Pull request merged**
