### PR TITLE
add doc comments for storage_context module

### PR DESCRIPTION
**Pull request by geometryolife**

### CODE REVIEW

**Comment by jolestar** [comment]
Need to update the documents.

**Comment by geometryolife** [comment]
> Need to update the documents.

done.

**Review by jolestar — APPROVED** [review]
Why so many document updates?

**Comment by geometryolife** [comment]
> Why so many document updates?

image

I simply ran this command (`rooch doc docgen`) in the current directory, need to specify a file right?

**Comment by jolestar** [comment]
run the genesis build to generate doc.

**Pull request merged**
