### PR TITLE
[gh-511] add ripemd-160 support for hashs.

### LINKED ISSUE #482: [bitcoin] support RIPEMD-160 hashing function.
Currently, there are two hash functions applied in Move for hash function:

1. KECCAK256
2. SHA256

Should there're supports for all bitcoin addresses derived from SHA-256 and RIPEMD-160 hashing functions, add a RIPEMD-160 hash function and verify its address generation logics in Move.

Task division:

1. https://github.com/rooch-network/fastcrypto/pull/2
2. #511

### LINKED ISSUE #511: [RIPEMD-160] add RIPEMD-160 hash function support.
Part of #482

### PR DESCRIPTION
**Pull request by feliciss**
Resolves #511 and closes #482.

### CODE REVIEW

**Comment by feliciss** [comment]
This PR is ready for review.

**Review by jolestar — APPROVED** [review]
LGTM

**Comment by jolestar** [comment]
Need to rebase and regenerate the genesis.

**Comment by feliciss** [comment]
Regenerated.

**Pull request merged**
