### PR TITLE
feat: Add jemalloc Memory Allocator Support

### PR DESCRIPTION
**Pull request by ZhangHanDong**
## Summary

Added `crates/rooch-alloc` to support the `jemalloc` memory allocator. 

> In high-performance applications that require frequent memory allocation and deallocation, using jemalloc can significantly improve performance and memory utilization.

The dependency has been introduced in the workspace, and related features can optionally be added in the child crates to include `rooch-alloc`.

This library is a modification of `tikv-alloc`, so some copyright notices in `rooch-alloc` still retain the `TikV-related `statements.

In the current PR, the `rooch-alloc` features are only added by default support to `rooch-executor` and `rooch-db` crates.

### CODE REVIEW

**Comment by jolestar** [comment]
.github/workflows/check_licenses.yml require `SPDX-License-Identifier: Apache-2.0`

**Comment by jolestar** [comment]
@popcnt1 help review

**Comment by ZhangHanDong** [comment]
@popcnt1 

I have done some memory analysis on the Mac platform using Xcode Instruments in combination with the current cargo bench. I will send some detailed data shortly.

**Comment by ZhangHanDong** [comment]
Figure 1 ：jemalloc
Figure 2 ：system


Both Figure 1 and Figure 2 are memory analysis graphs of the bench_tx_exec test results using Instruments. Figure 1 shows the results after using jemalloc, while Figure 2 shows the results using the system’s default allocator.

From the memory analysis, we can observe:

Figure 1:

- Memory allocation is very smooth, with almost no significant fluctuations. This indicates that the memory management system can efficiently handle a large number of memory allocation and deallocation requests.
- The low amount of persistent memory suggests that the program frequently allocates and deallocates memory, with most allocations being short-term. This indicates that the allocator can quickly allocate and free memory, maintaining efficient memory usage.

Figure 2:

- There are noticeable fluctuations in memory allocation, especially during allocation and deallocation, indicating a lack of smoothness. This suggests that the memory management system may have certain performance bottlenecks or memory fragmentation when handling allocation and deallocation requests.
- The higher amount of persistent memory usage indicates a greater number of long-term memory allocations. This may suggest that the memory management system is less efficient in freeing memory compared to Figure 1, resulting in more memory being occupied for a longer duration.

**Comment by jolestar** [comment]
@ZhangHanDong, please resolve the conflicts and build errors; I will merge this PR.

**Review by jolestar — APPROVED** [review]

**Comment by popcnt1** [comment]
@ZhangHanDong could u move this codes under rooch-common? It is a new crate for common libs

**Comment by ZhangHanDong** [comment]
@popcnt1 ok

**Comment by jolestar** [comment]
#2100 already introduced the jemalloc, should we close this PR?

**Comment by ZhangHanDong** [comment]
@jolestar  You can close this PR. I’ll open a new PR to make it to common lib.

**Pull request closed without merging**
